# -*- coding: utf-8 -*-
"""
build_glossary_v2.py — Từ điển v2 mở rộng (~500 mục)

Phủ các mảng:
  - Web / Frontend / Backend (mở rộng từ v1)
  - Cloud / DevOps / Infra   (mở rộng từ v1 + vá lỗi biên bản)
  - Bảo mật / Security       (MỚI)
  - AI / ML / Data           (MỚI)
  - Công cụ thiết kế & PM    (mở rộng từ v1)
  - Vá lỗi biên bản họp      (Claude Code, HTML/CSS, repository dạng lạ...)

Chạy:  python build_glossary_v2.py
Sinh ra glossary_v2.json (KHÔNG ghi đè v1 để an toàn).
Kiểm tra xong thì đổi tên thành glossary.json và khởi động lại backend.
"""
import json
from pathlib import Path


def t(term, ja_hears=(), vi_hears=(), vi_bad=(), ja_bad=(),
      vi_guard=(), ja_guard=()):
    return {
        "term": term,
        "ja_hears": list(ja_hears),
        "vi_hears": list(vi_hears),
        "vi_bad": list(vi_bad),
        "ja_bad": list(ja_bad),
        "vi_guard": list(vi_guard),
        "ja_guard": list(ja_guard),
    }


ENTRIES = [

    # =========================================================== GIT & MÃ NGUỒN
    t("git", ["ギット", "ギッド"], ["gít", "ghít"]),
    t("GitHub",
      ["ギットハブ", "ギッハブ", "ギットハップ", "ギithug", "ギthb", "ギthub"],
      ["gít háp", "ghít háp", "gít hắp", "gít hấp", "gít hắb"],
      vi_bad=["Githug", "Githab", "githug", "githab"]),
    t("GitLab", ["ギットラボ", "ギットラブ"], ["gít láp", "ghít láp"]),
    t("branch",
      ["ブランチ", "ブランチー"],
      ["bờ ranh", "bờ răn", "bờ ren"],
      vi_bad=["nhánh", "chi nhánh", "cành"],
      ja_bad=["ブランチ", "支店", "枝", "分岐"],
      vi_guard=["nhánh sông", "phân nhánh", "nhánh cây"]),
    t("merge",
      ["マージ", "マージー", "マーシ"],
      ["mơ dờ", "mớt dờ"],
      vi_bad=["hợp nhất", "sáp nhập", "gộp lại", "trộn"],
      ja_bad=["マージ", "統合", "結合", "合併"]),
    t("commit",
      ["コミット", "コミッド"],
      ["cô mít", "com mít", "cơ mít"],
      vi_bad=["cam kết", "giao phó", "commite"],
      ja_bad=["コミット", "約束"]),
    t("push", ["プッシュ"], ["pút sờ", "pút xờ"],
      vi_bad=["đẩy lên", "xô đẩy"],
      ja_bad=["プッシュ"]),
    t("pull", ["プル"], ["pun lờ"],
      vi_bad=["kéo về", "kéo xuống"],
      ja_bad=["プル"]),
    t("pull request",
      ["プルリクエスト", "プルリク", "プルリクエス"],
      ["pun ri quét", "pờ ri quét"],
      vi_bad=["yêu cầu kéo"],
      ja_bad=["プルリクエスト", "プルリク"]),
    t("conflict",
      ["コンフリクト", "コンフリ"],
      ["con phờ lích", "công lích"],
      vi_bad=["xung đột", "mâu thuẫn", "tranh chấp"],
      ja_bad=["コンフリクト", "衝突", "矛盾"]),
    t("repository",
      ["リポジトリ", "レポジトリ", "リポジトリー",
       "リポジト", "ビポジトリー", "リポジドリー", "リポジ"],
      ["rê pô", "ri pô", "rê pô si tô ri"],
      vi_bad=["kho lưu trữ", "kho chứa", "repositorium", "repositorie",
              "bản ghi", "Credit Reports"],
      ja_bad=["リポジトリ", "レポジトリ", "倉庫"]),
    t("repo", [], ["rê pô", "ri pô"]),
    t("clone", ["クローン"], ["cờ lôn", "cơ lôn"],
      vi_bad=["nhân bản", "sao chép"],
      ja_bad=["クローン", "複製"]),
    t("checkout", ["チェックアウト"], ["chếch ao", "chếch au"],
      ja_bad=["チェックアウト"]),
    t("rebase", ["リベース"], ["ri bết", "rê bết"],
      ja_bad=["リベース"]),
    t("tag", ["タグ"], ["tắc gờ"],
      vi_bad=["thẻ", "nhãn"],
      ja_bad=["タグ"]),
    t("release",
      ["リリース", "リリス"],
      ["ri lít", "rê lít", "ri li"],
      vi_bad=["phát hành", "ra mắt", "giải phóng", "thả ra"],
      ja_bad=["リリース", "解放", "釈放", "発売"]),
    t("version",
      ["バージョン", "バージョ"],
      ["vơ sần", "vơ giần"],
      vi_bad=["phiên bản"],
      ja_bad=["バージョン"]),
    t("source code", ["ソースコード"], ["sốt cốt", "sốt cô"],
      vi_bad=["mã nguồn"],
      ja_bad=["ソースコード"]),
    t("code", ["コード"], ["cốt", "cô đờ"],
      vi_bad=["mã"],
      ja_bad=["コード"],
      vi_guard=["mã số", "mã hóa", "mã hoá", "mã vạch", "mã sản phẩm"]),
    t("code review",
      ["コードレビュー", "行動review", "コー動reviewド"],
      ["cốt ri viu"],
      vi_bad=["review hành động", "review hành trình"],
      ja_bad=["コードレビュー"]),
    t("diff", ["ディフ", "差分"], ["đíp phờ"],
      vi_bad=["sự khác biệt"],
      ja_bad=["ディフ", "差分"]),
    t("patch", ["パッチ"], ["pát sờ", "pắt sờ"],
      vi_bad=["bản vá"],
      ja_bad=["パッチ"]),
    t("stash", ["スタッシュ"], ["x tát sờ"],
      ja_bad=["スタッシュ"]),
    t("fork", ["フォーク"], ["phô cờ"],
      vi_bad=["rẽ nhánh"],
      ja_bad=["フォーク"]),
    t("cherry-pick", ["チェリーピック"], ["chê ri pích"],
      ja_bad=["チェリーピック"]),

    # =========================================================== CI/CD & VẬN HÀNH
    t("CI/CD",
      ["シーアイシーディー", "シーアイ", "シーディー"],
      ["ci/cd", "xi ai xi đi", "si ai si đi", "xê i xê đê"],
      ja_bad=["シーアイシーディー"]),
    t("pipeline",
      ["パイプライン"],
      ["pai lai", "pắp lai", "pai pờ lai"],
      vi_bad=["đường ống"],
      ja_bad=["パイプライン"]),
    t("build", ["ビルド", "ビルト"], ["biu", "biu đờ"],
      vi_bad=["xây dựng"],
      ja_bad=["ビルド"],
      vi_guard=["xây dựng nhà", "xây dựng công trình"]),
    t("deploy",
      ["デプロイ", "デプロー", "デブロイ", "リプロイ"],
      ["đíp lôi", "đi lôi", "đì lôi", "đê lôi", "đi plôi"],
      vi_bad=["triển khai", "bố trí", "dàn trận"],
      ja_bad=["デプロイ", "展開", "配置", "配備"]),
    t("rollback", ["ロールバック"], ["rôn bách", "rôn bắc"],
      vi_bad=["quay lui", "hoàn tác"],
      ja_bad=["ロールバック", "巻き戻し"]),
    t("hotfix", ["ホットフィックス"], ["hót phích", "hót phít"],
      ja_bad=["ホットフィックス"]),
    t("staging", ["ステージング"], ["sờ tây dinh", "tây dinh"],
      ja_bad=["ステージング"]),
    t("production",
      ["プロダクション", "本番環境"],
      ["pờ rô đắc sần"],
      vi_bad=["sản xuất"],
      ja_bad=["プロダクション", "本番環境"],
      vi_guard=["nhà sản xuất", "sản xuất kinh doanh"]),
    t("Docker", ["ドッカー", "ドッカ"], ["đóc cơ", "đốc cơ", "đót cơ"],
      ja_bad=["ドッカー"]),
    t("Kubernetes",
      ["クバネティス", "クベルネテス", "クーベルネティス", "クバネテス"],
      ["cu bơ nét", "cu bơ nét tít", "ku bơ nét"],
      ja_bad=["クバネティス", "クベルネテス"]),
    t("container",
      ["コンテナ", "コンテナー"],
      ["công tây nơ", "con tây nơ"],
      vi_bad=["thùng chứa", "công-ten-nơ"],
      ja_bad=["コンテナ"]),
    t("image", ["イメージ"], ["i mết", "i mây dờ"],
      vi_bad=["hình ảnh"],
      ja_bad=["イメージ", "画像"],
      vi_guard=["hình ảnh đẹp"]),
    t("Jenkins", ["ジェンキンス", "ゼンキンス"], ["gien kin", "den kin"],
      ja_bad=["ジェンキンス"]),
    t("GitHub Actions", ["ギットハブアクション"], ["gít háp ắc sần"],
      ja_bad=["ギットハブアクション"]),
    t("GitLab CI", ["ギットラボシーアイ"], [],
      ja_bad=["ギットラボシーアイ"]),
    t("ArgoCD", ["アルゴシーディー"], ["á go xi đi"],
      ja_bad=["アルゴシーディー"]),
    t("Helm", ["ヘルム"], ["hem mờ"],
      ja_bad=["ヘルム"]),
    t("namespace", ["ネームスペース"], ["nêm sờ pết"],
      vi_bad=["không gian tên"],
      ja_bad=["ネームスペース"]),
    t("pod", ["ポッド"], ["pót đờ"],
      ja_bad=["ポッド"]),
    t("cluster", ["クラスター", "クラスタ"], ["cờ lát tơ", "cơ lát tơ"],
      vi_bad=["cụm"],
      ja_bad=["クラスター", "クラスタ"]),
    t("node", ["ノード"], ["nốt đờ"],
      vi_bad=["nút mạng"],
      ja_bad=["ノード"]),
    t("load balancer",
      ["ロードバランサー", "ロードバランサ"],
      ["lốt ba lần xơ"],
      vi_bad=["cân bằng tải"],
      ja_bad=["ロードバランサー"]),
    t("auto scaling",
      ["オートスケーリング"],
      ["ô tô xờ kết linh"],
      vi_bad=["tự động mở rộng"],
      ja_bad=["オートスケーリング"]),
    t("Terraform", ["テラフォーム"], ["tê ra phôm"],
      ja_bad=["テラフォーム"]),
    t("Ansible", ["アンシブル"], ["an xi bồ"],
      ja_bad=["アンシブル"]),
    t("Prometheus", ["プロメテウス"], ["pờ rô mê tê uýt"],
      ja_bad=["プロメテウス"]),
    t("Grafana", ["グラファナ"], ["gờ ra pha na"],
      ja_bad=["グラファナ"]),
    t("Datadog", ["データドッグ"], ["đa ta đóc"],
      ja_bad=["データドッグ"]),

    # =========================================================== CLOUD & DỊCH VỤ
    t("server", ["サーバー", "サーバ"], ["sơ vơ", "xơ vơ", "sờ vờ"],
      vi_bad=["máy chủ"],
      ja_bad=["サーバー", "サーバ"]),
    t("client",
      ["クライアント"],
      ["cờ lai ần", "cơ lai ừn", "lai ần"],
      vi_bad=["khách hàng", "máy khách"],
      ja_bad=["クライアント", "顧客"],
      vi_guard=["chăm sóc khách hàng"]),
    t("cloud", ["クラウド"], ["cờ lao", "cơ lao"],
      vi_bad=["đám mây"],
      ja_bad=["クラウド", "雲"]),
    t("AWS",
      ["エーダブリューエス", "エーダブルエス", "アマゾンウェブサービス"],
      ["aws", "a vê ét", "ây đắp liu ét"],
      ja_bad=["エーダブリューエス"]),
    t("Azure", ["アジュール", "アズール", "アジャー"],
      ["a dua", "a diua"],
      ja_bad=["アジュール", "アズール"]),
    t("GCP",
      ["ジーシーピー", "グーグルクラウド"],
      ["gcp", "gi xi pi"],
      ja_bad=["ジーシーピー"]),
    t("EC2", ["イーシーツー"], ["i xi tu"],
      ja_bad=["イーシーツー"]),
    t("S3", ["エスリー", "エススリー"], ["ét thờ ri"],
      ja_bad=["エスリー"]),
    t("Lambda", ["ラムダ"], ["lăm đa"],
      ja_bad=["ラムダ"]),
    t("RDS", ["アールディーエス"], ["rds", "a đi ét"],
      ja_bad=["アールディーエス"]),
    t("ECS", ["イーシーエス"], ["ecs", "i xi ét"],
      ja_bad=["イーシーエス"]),
    t("EKS", ["イーケーエス"], ["eks", "i kê ét"],
      ja_bad=["イーケーエス"]),
    t("CloudFront", ["クラウドフロント"], ["cờ lao phờ rông"],
      ja_bad=["クラウドフロント"]),
    t("VPC", ["ブイピーシー"], ["vpc", "vi pi xi"],
      ja_bad=["ブイピーシー"]),
    t("IAM", ["アイエーエム"], ["iam", "ai ây em"],
      ja_bad=["アイエーエム"]),
    t("SQS", ["エスキューエス"], ["sqs", "ét qiu ét"],
      ja_bad=["エスキューエス"]),
    t("SNS", ["エスエヌエス"], ["sns", "ét en ét"],
      ja_bad=["エスエヌエス"]),
    t("network",
      ["ネットワーク"],
      ["nét quớc", "nét guơ"],
      vi_bad=["mạng lưới"],
      ja_bad=["ネットワーク"]),
    t("VPN", ["ブイピーエヌ"], ["vpn", "vi pi en"],
      ja_bad=["ブイピーエヌ"]),
    t("firewall", ["ファイアウォール"], ["phai ô uôn", "phai ô wo"],
      vi_bad=["tường lửa"],
      ja_bad=["ファイアウォール"]),
    t("DNS", ["ディーエヌエス"], ["dns", "đi en ét"],
      ja_bad=["ディーエヌエス"]),
    t("CDN", ["シーディーエヌ"], ["cdn", "xi đi en"],
      ja_bad=["シーディーエヌ"]),
    t("backup", ["バックアップ"], ["bách ắp", "bắc cắp"],
      vi_bad=["sao lưu"],
      ja_bad=["バックアップ"]),
    t("restore", ["リストア"], ["rít to", "ri sờ to"],
      vi_bad=["khôi phục"],
      ja_bad=["リストア", "復元"]),
    t("monitoring", ["モニタリング"], ["mô ni tơ ring"],
      vi_bad=["giám sát"],
      ja_bad=["モニタリング", "監視"]),
    t("alert", ["アラート"], ["a lớt", "a lợt"],
      vi_bad=["cảnh báo"],
      ja_bad=["アラート", "警報"]),
    t("incident", ["インシデント"], ["in si đần", "in xi đần"],
      vi_bad=["sự cố"],
      ja_bad=["インシデント"]),
    t("log", ["ログ"], ["lóc gờ"],
      vi_bad=["nhật ký"],
      ja_bad=["ログ", "記録"]),
    t("on-premise", ["オンプレミス", "オンプレ"], ["on pờ rem", "on pre"],
      vi_bad=["tại chỗ", "nội bộ"],
      ja_bad=["オンプレミス", "オンプレ"]),
    t("hybrid cloud", ["ハイブリッドクラウド"], ["hai bờ rít cờ lao"],
      ja_bad=["ハイブリッドクラウド"]),
    t("microservice",
      ["マイクロサービス"],
      ["mai cờ rô xơ vít", "mai cờ rô sờ vít"],
      vi_bad=["dịch vụ nhỏ"],
      ja_bad=["マイクロサービス"]),
    t("serverless", ["サーバーレス"], ["sờ vờ lét", "sơ vơ lét"],
      vi_bad=["không máy chủ"],
      ja_bad=["サーバーレス"]),
    t("SLA", ["エスエルエー"], ["sla", "ét el ây"],
      ja_bad=["エスエルエー"]),
    t("SLO", ["エスエルオー"], ["slo", "ét el ô"],
      ja_bad=["エスエルオー"]),
    t("uptime", ["アップタイム"], ["áp thai"],
      vi_bad=["thời gian hoạt động"],
      ja_bad=["アップタイム"]),
    t("downtime", ["ダウンタイム"], ["đao thai"],
      vi_bad=["thời gian ngừng hoạt động"],
      ja_bad=["ダウンタイム"]),
    t("disaster recovery",
      ["ディザスターリカバリー"],
      ["đi sá tơ ri cơ vơ ri"],
      vi_bad=["phục hồi thảm họa"],
      ja_bad=["ディザスターリカバリー"]),

    # =========================================================== PHÁT TRIỂN WEB / APP
    t("HTML",
      ["エイチティーエムエル", "ハイパーテキスト"],
      ["html", "ây tê em el", "ây ti em el", "hdm", "hd mờ"],
      vi_bad=["ngôn ngữ đánh dấu"],
      ja_bad=["エイチティーエムエル"]),
    t("CSS",
      ["シーエスエス"],
      ["css", "xi ét ét", "xi ét xì", "xi ét x", "cs"],
      ja_bad=["シーエスエス"]),
    t("JavaScript",
      ["ジャバスクリプト", "ジャバスクリ"],
      ["gia va sờ crip", "gia va x crip", "java sờ crip"],
      vi_bad=["kịch bản Java"],
      ja_bad=["ジャバスクリプト"]),
    t("TypeScript",
      ["タイプスクリプト", "タイプスクリ"],
      ["tai pờ sờ crip", "tai pờ x crip"],
      ja_bad=["タイプスクリプト"]),
    t("React",
      ["リアクト", "リアクト"],
      ["ri ắc", "rê ắc"],
      ja_bad=["リアクト"]),
    t("Vue", ["ビュー"], ["viu", "biêu"],
      ja_bad=["ビュー"]),
    t("Angular", ["アンギュラー", "アンギュラ"], ["an giu lơ"],
      ja_bad=["アンギュラー"]),
    t("Node.js",
      ["ノードジェイエス", "ノード"],
      ["nốt đê giây ét", "nốt giây ét"],
      vi_bad=["máy chủ Node"],
      ja_bad=["ノードジェイエス"]),
    t("npm", ["エヌピーエム"], ["npm", "en pi em"],
      ja_bad=["エヌピーエム"]),
    t("yarn", ["ヤーン"], ["gia nờ"],
      ja_bad=["ヤーン"]),
    t("webpack", ["ウェブパック"], ["guép pắc"],
      ja_bad=["ウェブパック"]),
    t("Vite", ["ビット", "ヴィート"], ["vít", "vi tờ"],
      ja_bad=["ビット", "ヴィート"]),
    t("REST", ["レスト", "レストAPI"], ["rét", "rét xt"],
      ja_bad=["レスト"]),
    t("GraphQL", ["グラフキューエル"], ["gờ ra phờ qiu el"],
      ja_bad=["グラフキューエル"]),
    t("WebSocket", ["ウェブソケット"], ["guép sô két"],
      ja_bad=["ウェブソケット"]),
    t("HTTP", ["エイチティーティーピー"], ["http", "ây ti ti pi"],
      ja_bad=["エイチティーティーピー"]),
    t("HTTPS", ["エイチティーティーピーエス"], ["https", "ây ti ti pi ét"],
      ja_bad=["エイチティーティーピーエス"]),
    t("JSON", ["ジェイソン"], ["json", "gei sần", "gei sơn"],
      vi_bad=["đối tượng JSON"],
      ja_bad=["ジェイソン"]),
    t("XML", ["エックスエムエル"], ["xml", "ếch em el"],
      ja_bad=["エックスエムエル"]),
    t("YAML", ["ヤムル", "ヤーメル"], ["yaml", "ia mồ"],
      ja_bad=["ヤムル", "ヤーメル"]),
    t("Docker Compose",
      ["ドッカーコンポーズ"],
      ["đóc cơ com pô"],
      ja_bad=["ドッカーコンポーズ"]),
    t("nginx", ["エンジンエックス", "ニンクス"], ["en gin ếch", "nin ếch"],
      ja_bad=["エンジンエックス"]),
    t("Apache", ["アパッチ"], ["a pát sì"],
      ja_bad=["アパッチ"]),
    t("proxy", ["プロキシ"], ["pờ rô xi", "pro xi"],
      vi_bad=["máy chủ proxy", "trung gian"],
      ja_bad=["プロキシ"]),
    t("middleware", ["ミドルウェア"], ["mít đồ guê"],
      vi_bad=["phần mềm trung gian"],
      ja_bad=["ミドルウェア"]),
    t("cookie", ["クッキー"], ["cu ki"],
      ja_bad=["クッキー"]),
    t("session", ["セッション"], ["xê sần", "sê sừn"],
      vi_bad=["phiên đăng nhập"],
      ja_bad=["セッション"]),
    t("JWT", ["ジェイダブリューティー"], ["jwt", "gei đắp liu ti"],
      ja_bad=["ジェイダブリューティー"]),
    t("OAuth", ["オーオース", "オーエーユース"], ["o oth", "ô oth"],
      ja_bad=["オーオース"]),
    t("responsive", ["レスポンシブ"], ["rét pôn xi bờ"],
      vi_bad=["đáp ứng"],
      ja_bad=["レスポンシブ"]),
    t("PWA", ["ピーダブリューエー"], ["pwa", "pi đắp liu ây"],
      ja_bad=["ピーダブリューエー"]),
    t("SPA", ["エスピーエー"], ["spa", "ét pi ây"],
      ja_bad=["エスピーエー"]),
    t("SSR", ["エスエスアール"], ["ssr", "ét ét a"],
      ja_bad=["エスエスアール"]),
    t("SSG", ["エスエスジー"], ["ssg", "ét ét gi"],
      ja_bad=["エスエスジー"]),

    # =========================================================== DATABASE & DATA
    t("database",
      ["データベース", "デービー", "ディービー"],
      ["đa ta bây", "đây ta bây", "đa ta bết"],
      vi_bad=["cơ sở dữ liệu"],
      ja_bad=["データベース"]),
    t("data", ["データ"], ["đa ta", "đây ta"],
      vi_bad=["dữ liệu"],
      ja_bad=["データ"]),
    t("SQL", ["エスキューエル", "シークェル"],
      ["sql", "ét kiu eo", "ét qiu eo"],
      ja_bad=["エスキューエル"]),
    t("NoSQL", ["ノーエスキューエル"], ["no sql", "nô ét kiu eo"],
      ja_bad=["ノーエスキューエル"]),
    t("MySQL", ["マイエスキューエル"], ["mai sql", "mai ét kiu eo"],
      ja_bad=["マイエスキューエル"]),
    t("PostgreSQL",
      ["ポストグレエスキューエル", "ポスグレ"],
      ["pốt gờ rét sql", "post gờ rét"],
      ja_bad=["ポストグレエスキューエル", "ポスグレ"]),
    t("MongoDB", ["モンゴディービー"], ["mon gô đi bi"],
      ja_bad=["モンゴディービー"]),
    t("Redis", ["レディス", "レジス"], ["rê đit", "rê đít"],
      ja_bad=["レディス"]),
    t("Elasticsearch",
      ["エラスティックサーチ"],
      ["ê lát tích sớt"],
      ja_bad=["エラスティックサーチ"]),
    t("query", ["クエリ", "クエリー"], ["qué ri", "quê ri"],
      vi_bad=["truy vấn"],
      ja_bad=["クエリ"]),
    t("schema", ["スキーマ"], ["x kê ma", "sờ kê ma"],
      vi_bad=["lược đồ"],
      ja_bad=["スキーマ"]),
    t("index", ["インデックス"], ["in đếch", "in đét"],
      vi_bad=["chỉ mục"],
      ja_bad=["インデックス"]),
    t("migration", ["マイグレーション"], ["mai gờ rê sần"],
      vi_bad=["di chuyển", "chuyển đổi"],
      ja_bad=["マイグレーション"]),
    t("transaction", ["トランザクション"], ["tờ ran sắc sần", "tờ zan sắc sần"],
      vi_bad=["giao dịch"],
      ja_bad=["トランザクション"]),
    t("ORM", ["オーアールエム"], ["orm", "ô a em"],
      ja_bad=["オーアールエム"]),
    t("ETL", ["イーティーエル"], ["etl", "i ti el"],
      ja_bad=["イーティーエル"]),
    t("data pipeline",
      ["データパイプライン"],
      ["đa ta pai lai"],
      vi_bad=["đường ống dữ liệu"],
      ja_bad=["データパイプライン"]),
    t("data warehouse",
      ["データウェアハウス"],
      ["đa ta guê hao"],
      vi_bad=["kho dữ liệu"],
      ja_bad=["データウェアハウス"]),
    t("data lake", ["データレイク"], ["đa ta lếch"],
      vi_bad=["hồ dữ liệu"],
      ja_bad=["データレイク"]),
    t("Kafka", ["カフカ"], ["ca pha ca"],
      ja_bad=["カフカ"]),
    t("Spark", ["スパーク"], ["x pắc"],
      ja_bad=["スパーク"]),
    t("Airflow", ["エアフロー"], ["ê a phlô"],
      ja_bad=["エアフロー"]),
    t("BigQuery", ["ビッグクエリ"], ["bích qué ri"],
      ja_bad=["ビッグクエリ"]),
    t("Snowflake", ["スノーフレーク"], ["x nô phlếch"],
      ja_bad=["スノーフレーク"]),
    t("dashboard", ["ダッシュボード"], ["đát sờ bô"],
      vi_bad=["bảng điều khiển"],
      ja_bad=["ダッシュボード"]),

    # =========================================================== AI / ML
    t("AI", ["エーアイ"], ["ây ai"],
      vi_bad=["trí tuệ nhân tạo"],
      ja_bad=["エーアイ", "人工知能"]),
    t("machine learning",
      ["マシンラーニング", "機械学習"],
      ["ma sìn lơ ninh", "ma sin lơ ninh"],
      vi_bad=["học máy"],
      ja_bad=["マシンラーニング", "機械学習"]),
    t("deep learning",
      ["ディープラーニング", "深層学習"],
      ["đíp lơ ninh"],
      vi_bad=["học sâu"],
      ja_bad=["ディープラーニング", "深層学習"]),
    t("model", ["モデル"], ["mô đồ", "mô đề"],
      vi_bad=["mô hình"],
      ja_bad=["モデル"],
      vi_guard=["mô hình kinh doanh", "người mẫu"]),
    t("training", ["トレーニング"], ["tờ rê ninh"],
      vi_bad=["đào tạo", "huấn luyện"],
      ja_bad=["トレーニング"],
      vi_guard=["đào tạo nhân viên", "huấn luyện viên"]),
    t("inference", ["インファレンス"], ["in phờ rần"],
      vi_bad=["suy luận"],
      ja_bad=["インファレンス"]),
    t("neural network",
      ["ニューラルネットワーク"],
      ["niu rồ nét quớc"],
      vi_bad=["mạng nơ-ron"],
      ja_bad=["ニューラルネットワーク"]),
    t("LLM", ["エルエルエム"], ["llm", "el el em"],
      ja_bad=["エルエルエム"]),
    t("GPT", ["ジーピーティー"], ["gpt", "gi pi ti"],
      ja_bad=["ジーピーティー"]),
    t("ChatGPT",
      ["チャットジーピーティー", "チャットGPT"],
      ["chát di pi ti", "chát gi bi ti"],
      ja_bad=["チャットジーピーティー"]),
    t("Claude",
      ["クロード", "クロードAI"],
      ["cờ lốt", "cờ lô đờ"],
      vi_bad=["Clood", "code lạnh"],
      ja_bad=["クロード"]),
    t("Claude Code",
      ["クロードコード", "クロドcode"],
      ["cờ lốt cốt", "cờ lô đờ cốt"],
      vi_bad=["Cloodcode", "code lạnh", "cờ rốt code"],
      ja_bad=["クロードコード"]),
    t("Gemini", ["ジェミニ"], ["gê mi ni"],
      ja_bad=["ジェミニ"]),
    t("Copilot", ["コパイロット"], ["cô pai lót"],
      vi_bad=["phi công phụ"],
      ja_bad=["コパイロット"]),
    t("prompt", ["プロンプト"], ["pờ rom", "pờ răm"],
      vi_bad=["lời nhắc", "câu lệnh"],
      ja_bad=["プロンプト"]),
    t("fine-tuning", ["ファインチューニング"], ["phai tuyn ninh"],
      vi_bad=["tinh chỉnh"],
      ja_bad=["ファインチューニング"]),
    t("embedding", ["エンベディング"], ["em bét dinh"],
      vi_bad=["nhúng"],
      ja_bad=["エンベディング"]),
    t("token", ["トークン"], ["tô cần", "tô kừn"],
      ja_bad=["トークン"]),
    t("RAG", ["ラグ", "アールエージー"], ["rag", "a ây gi"],
      ja_bad=["ラグ", "アールエージー"]),
    t("vector database",
      ["ベクターデータベース"],
      ["vec tơ đa ta bây"],
      vi_bad=["cơ sở dữ liệu vector"],
      ja_bad=["ベクターデータベース"]),
    t("OpenAI", ["オープンエーアイ"], ["ô pần ây ai"],
      ja_bad=["オープンエーアイ"]),
    t("Hugging Face", ["ハギングフェイス"], ["hăc king phếch"],
      ja_bad=["ハギングフェイス"]),
    t("PyTorch", ["パイトーチ"], ["pai tót sờ"],
      ja_bad=["パイトーチ"]),
    t("TensorFlow", ["テンソルフロー"], ["ten sồ phờ lô"],
      ja_bad=["テンソルフロー"]),
    t("Jupyter", ["ジュピター"], ["giu pi tơ"],
      ja_bad=["ジュピター"]),
    t("Python", ["パイソン", "ピソン"], ["pai sần", "pi sần"],
      ja_bad=["パイソン"]),
    t("vibe coding",
      ["バイブコーディング"],
      ["vai bờ cốt dinh", "vai bờ cô đình"],
      vi_bad=["vấn đề đầu vào", "lập trình cảm hứng"],
      ja_bad=["バイブコーディング"]),
    t("accuracy", ["アキュラシー"], ["a kiu ra xi"],
      vi_bad=["độ chính xác"],
      ja_bad=["アキュラシー"]),
    t("dataset", ["データセット"], ["đa ta xết"],
      vi_bad=["tập dữ liệu"],
      ja_bad=["データセット"]),
    t("preprocessing",
      ["前処理", "プリプロセシング"],
      ["pờ ri pờ rô xét xinh"],
      vi_bad=["tiền xử lý"],
      ja_bad=["前処理", "プリプロセシング"]),
    t("GPU", ["ジーピーユー"], ["gpu", "gi pi diu"],
      ja_bad=["ジーピーユー"]),
    t("batch", ["バッチ"], ["bát sờ", "bác sờ"],
      vi_bad=["lô", "nhóm"],
      ja_bad=["バッチ"]),

    # =========================================================== BẢO MẬT / SECURITY
    t("security",
      ["セキュリティ", "セキュリティー"],
      ["sê kiu ri ti", "xê kiu ri ti"],
      vi_bad=["bảo mật", "an ninh"],
      ja_bad=["セキュリティ"],
      vi_guard=["an ninh trật tự", "an ninh quốc gia"]),
    t("vulnerability",
      ["脆弱性", "バルネラビリティ"],
      ["vôn nơ ra bi li ti"],
      vi_bad=["lỗ hổng bảo mật", "điểm yếu"],
      ja_bad=["脆弱性", "バルネラビリティ"]),
    t("CVE", ["シーブイイー"], ["cve", "xi vi i"],
      ja_bad=["シーブイイー"]),
    t("penetration test",
      ["ペネトレーションテスト", "ペネトレ"],
      ["pe nê trê sần tét", "pén tét"],
      vi_bad=["kiểm tra xâm nhập"],
      ja_bad=["ペネトレーションテスト"]),
    t("encryption",
      ["暗号化", "エンクリプション"],
      ["en cờ ríp sần"],
      vi_bad=["mã hóa", "mã hoá"],
      ja_bad=["暗号化", "エンクリプション"],
      vi_guard=["giải mã hóa"]),
    t("SSL", ["エスエスエル"], ["ssl", "ét ét el"],
      ja_bad=["エスエスエル"]),
    t("TLS", ["ティーエルエス"], ["tls", "ti el ét"],
      ja_bad=["ティーエルエス"]),
    t("certificate", ["証明書", "サーティフィケート"],
      ["xơ ti phi cết"],
      vi_bad=["chứng chỉ", "chứng nhận"],
      ja_bad=["証明書", "サーティフィケート"]),
    t("authentication",
      ["認証", "オーセンティケーション"],
      ["ô then ti kê sần"],
      vi_bad=["xác thực", "xác minh"],
      ja_bad=["認証", "オーセンティケーション"]),
    t("authorization",
      ["認可", "オーソライゼーション"],
      ["ô thô ri zê sần"],
      vi_bad=["phân quyền", "ủy quyền"],
      ja_bad=["認可", "オーソライゼーション"]),
    t("RBAC", ["アールバック", "ロールベースアクセス"],
      ["rbac", "a bắc"],
      ja_bad=["アールバック"]),
    t("zero trust", ["ゼロトラスト"], ["dê rô tờ rắt"],
      vi_bad=["không tin tưởng"],
      ja_bad=["ゼロトラスト"]),
    t("WAF", ["ダブリューエーエフ"], ["waf", "đắp liu ây ép"],
      ja_bad=["ダブリューエーエフ"]),
    t("DDoS", ["ディードス", "ディーオーエス"], ["ddos", "đi đô ét"],
      ja_bad=["ディードス"]),
    t("phishing", ["フィッシング"], ["phít xinh", "phít sing"],
      vi_bad=["lừa đảo trực tuyến"],
      ja_bad=["フィッシング"]),
    t("malware", ["マルウェア"], ["ma oa"],
      vi_bad=["phần mềm độc hại"],
      ja_bad=["マルウェア"]),
    t("ransomware", ["ランサムウェア"], ["ran xồm guê"],
      vi_bad=["mã độc tống tiền"],
      ja_bad=["ランサムウェア"]),
    t("sandbox", ["サンドボックス"], ["xan bóc"],
      vi_bad=["môi trường cô lập"],
      ja_bad=["サンドボックス"]),
    t("access control", ["アクセス制御"], ["ắc xét cần trôn"],
      vi_bad=["kiểm soát truy cập"],
      ja_bad=["アクセス制御"]),
    t("audit log", ["監査ログ"], ["ô đit lóc"],
      vi_bad=["nhật ký kiểm tra"],
      ja_bad=["監査ログ"]),
    t("secret", ["シークレット"], ["xi cờ rết"],
      vi_bad=["bí mật"],
      ja_bad=["シークレット", "秘密"],
      vi_guard=["giữ bí mật", "bí mật quốc gia"]),
    t("2FA", ["ツーエフエー"], ["2fa", "tu ép ây"],
      ja_bad=["ツーエフエー"]),
    t("MFA", ["エムエフエー"], ["mfa", "em ép ây"],
      ja_bad=["エムエフエー"]),
    t("SIEM", ["シーム"], ["siem", "xi em"],
      ja_bad=["シーム"]),
    t("SOC", ["ソック"], ["soc", "xóc"],
      ja_bad=["ソック"]),
    # =========================================================== CODE & THIẾT KẾ
    t("API", ["エーピーアイ", "エイピーアイ"],
      ["api", "ây pi ai", "a pi ai", "ây bi ai"],
      ja_bad=["エーピーアイ"]),
    t("API key", ["エーピーアイキー"],
      ["api key", "ây pi ai ki"],
      ja_bad=["エーピーアイキー"]),
    t("endpoint", ["エンドポイント"],
      ["en poin", "en pon"],
      ja_bad=["エンドポイント"]),
    t("framework",
      ["フレームワーク"],
      ["phờ rêm guơ", "phrêm quớc"],
      vi_bad=["khung làm việc", "khuôn khổ"],
      ja_bad=["フレームワーク"]),
    t("library",
      ["ライブラリ", "ライブラリー"],
      ["lai bờ ra ri", "lai bra ri"],
      vi_bad=["thư viện"],
      ja_bad=["ライブラリ", "図書館"],
      vi_guard=["thư viện trường", "thư viện quốc gia"]),
    t("module", ["モジュール"], ["mô điun", "mô đun"],
      ja_bad=["モジュール"]),
    t("package", ["パッケージ"], ["pắc cét", "pác két"],
      vi_bad=["gói"],
      ja_bad=["パッケージ"]),
    t("dependency", ["依存性", "ディペンデンシー"],
      ["đi pen đần xi"],
      vi_bad=["phụ thuộc"],
      ja_bad=["依存性", "ディペンデンシー"]),
    t("function", ["ファンクション"], ["phăng sần"],
      vi_bad=["chức năng", "hàm số"],
      ja_bad=["ファンクション", "機能"],
      vi_guard=["chức năng nhiệm vụ"]),
    t("class", ["クラス"], ["cờ lát", "cơ lát"],
      vi_bad=["lớp học"],
      ja_bad=["クラス"]),
    t("method", ["メソッド"], ["mê thót", "mê sót"],
      vi_bad=["phương thức", "phương pháp"],
      ja_bad=["メソッド", "方法"]),
    t("interface", ["インターフェース", "インターフェイス"],
      ["in tơ phết", "in tơ phếch"],
      vi_bad=["giao diện"],
      ja_bad=["インターフェース"],
      vi_guard=["giao diện người dùng"]),
    t("abstract", ["抽象", "アブストラクト"], ["áp x tờ rắc"],
      vi_bad=["trừu tượng"],
      ja_bad=["抽象", "アブストラクト"]),
    t("inheritance", ["継承", "インヘリタンス"], ["in hê ri tần"],
      vi_bad=["kế thừa"],
      ja_bad=["継承", "インヘリタンス"]),
    t("polymorphism",
      ["ポリモーフィズム"],
      ["po li mo phít dờm"],
      vi_bad=["đa hình"],
      ja_bad=["ポリモーフィズム"]),
    t("design pattern",
      ["デザインパターン"],
      ["đi dain pát tơn"],
      vi_bad=["mẫu thiết kế"],
      ja_bad=["デザインパターン"]),
    t("architecture",
      ["アーキテクチャ"],
      ["a ki tét chờ"],
      vi_bad=["kiến trúc"],
      ja_bad=["アーキテクチャ"],
      vi_guard=["kiến trúc xây dựng"]),
    t("MVC", ["エムブイシー"], ["mvc", "em vi xi"],
      ja_bad=["エムブイシー"]),
    t("SOLID", ["ソリッド"], ["so lít"],
      ja_bad=["ソリッド"]),
    t("DRY", ["ドライ"], ["đờ rai"],
      ja_bad=["ドライ"]),
    t("KISS", ["キス"], ["kít"],
      ja_bad=["キス"]),
    t("performance",
      ["パフォーマンス"],
      ["pơ pho mần"],
      vi_bad=["hiệu năng", "hiệu suất", "màn trình diễn"],
      ja_bad=["パフォーマンス", "性能"]),
    t("memory", ["メモリ", "メモリー"], ["mê mô ri"],
      vi_bad=["bộ nhớ", "trí nhớ", "ký ức"],
      ja_bad=["メモリ", "記憶"]),
    t("cache", ["キャッシュ"], ["cách sờ"],
      vi_bad=["bộ nhớ đệm", "tiền mặt"],
      ja_bad=["キャッシュ"]),
    t("CPU", ["シーピーユー"], ["cpu", "xi pi diu"],
      ja_bad=["シーピーユー"]),
    t("RAM", ["ラム"], ["ram", "ram mờ"],
      ja_bad=["ラム"]),
    t("SSD", ["エスエスディー"], ["ssd", "ét ét đi"],
      ja_bad=["エスエスディー"]),
    t("refactor",
      ["リファクタリング", "リファクタ"],
      ["ri phách tơ"],
      vi_bad=["tái cấu trúc"],
      ja_bad=["リファクタリング"]),
    t("spec", ["スペック", "仕様書"], ["sờ pếch"],
      vi_bad=["thông số", "đặc tả"],
      ja_bad=["スペック", "仕様書"]),
    t("test", ["テスト"], ["tét"],
      vi_bad=["kiểm tra", "kiểm thử", "thử nghiệm"],
      ja_bad=["テスト", "試験"],
      vi_guard=["kiểm tra sức khỏe", "kiểm tra lại thông tin"]),
    t("unit test",
      ["ユニットテスト", "単体テスト"],
      ["diu nít tét", "iu nít tét"],
      ja_bad=["ユニットテスト", "単体テスト"]),
    t("integration test",
      ["結合テスト", "インテグレーションテスト"],
      [],
      ja_bad=["結合テスト"]),
    t("e2e test",
      ["エンドツーエンドテスト", "E2Eテスト"],
      ["i tu i tét"],
      ja_bad=["エンドツーエンドテスト"]),
    t("mock", ["モック"], ["móc cờ"],
      ja_bad=["モック"]),
    t("coverage", ["カバレッジ"], ["ca vơ rếch"],
      vi_bad=["độ phủ"],
      ja_bad=["カバレッジ"]),
    t("bug", ["バグ", "バーグ"], ["bấc gờ", "bặc gờ"],
      vi_bad=["lỗi", "con bọ", "sâu bọ"],
      ja_bad=["バグ", "虫"],
      vi_guard=["xin lỗi", "lỗi lầm", "có lỗi với", "lỗi hẹn"]),
    t("fix", ["フィックス"], ["phích", "phít"],
      ja_bad=["フィックス"]),
    t("debug", ["デバッグ", "デバック"], ["đi bấc", "đê bấc"],
      vi_bad=["gỡ lỗi", "gỡ rối"],
      ja_bad=["デバッグ"]),
    t("error", ["エラー"], ["e rơ", "ê rơ"],
      ja_bad=["エラー"]),
    t("exception", ["例外", "エクセプション"], ["ếch xép sần"],
      vi_bad=["ngoại lệ"],
      ja_bad=["例外", "エクセプション"]),
    t("stack trace", ["スタックトレース"], ["x tắc tờ rết"],
      vi_bad=["dấu vết lỗi"],
      ja_bad=["スタックトレース"]),
    t("breakpoint", ["ブレークポイント"], ["bờ rếch poin"],
      vi_bad=["điểm dừng"],
      ja_bad=["ブレークポイント"]),

    # =========================================================== THIẾT KẾ & UX
    t("UI", ["ユーアイ"], ["ui", "diu ai"],
      vi_bad=["giao diện người dùng"],
      ja_bad=["ユーアイ"]),
    t("UX", ["ユーエックス"], ["ux", "diu ếch"],
      vi_bad=["trải nghiệm người dùng"],
      ja_bad=["ユーエックス"]),
    t("Figma", ["フィグマ"], ["phích ma", "phíc ma"],
      ja_bad=["フィグマ"]),
    t("wireframe", ["ワイヤーフレーム"], ["guai ơ phrêm"],
      vi_bad=["bản phác thảo"],
      ja_bad=["ワイヤーフレーム"]),
    t("prototype", ["プロトタイプ"], ["pờ rô tô tai"],
      vi_bad=["nguyên mẫu"],
      ja_bad=["プロトタイプ"]),
    t("mockup", ["モックアップ"], ["móc ắp"],
      vi_bad=["bản mô phỏng"],
      ja_bad=["モックアップ"]),
    t("design system",
      ["デザインシステム"],
      ["đi dain xít tem"],
      vi_bad=["hệ thống thiết kế"],
      ja_bad=["デザインシステム"]),
    t("component", ["コンポーネント"], ["com pô nần"],
      vi_bad=["thành phần"],
      ja_bad=["コンポーネント"]),
    t("pixel", ["ピクセル"], ["pích xồ"],
      ja_bad=["ピクセル"]),
    t("accessibility",
      ["アクセシビリティ"],
      ["ắc xét xi bi li ti"],
      vi_bad=["khả năng tiếp cận"],
      ja_bad=["アクセシビリティ"]),
    t("Adobe", ["アドビ"], ["a đô bi"],
      ja_bad=["アドビ"]),

    # =========================================================== QUẢN LÝ DỰ ÁN
    t("task", ["タスク"], ["tát sờ", "tát cờ"],
      vi_bad=["nhiệm vụ", "công việc"],
      ja_bad=["タスク"],
      vi_guard=["công việc gia đình", "nhiệm vụ chính trị"]),
    t("ticket", ["チケット"], ["tích két", "ti két"],
      vi_bad=["vé"],
      ja_bad=["チケット"],
      vi_guard=["vé máy bay", "vé xe", "vé tàu"]),
    t("issue", ["イシュー", "イッシュー"], ["i siu", "ít siu"],
      vi_bad=["vấn đề"],
      ja_bad=["イシュー", "問題"],
      vi_guard=["vấn đề sức khỏe"]),
    t("backlog", ["バックログ"], ["bách lóc", "bắc lóc"],
      ja_bad=["バックログ"]),
    t("sprint", ["スプリント"], ["sờ prin", "x prin"],
      vi_bad=["chạy nước rút"],
      ja_bad=["スプリント"]),
    t("scrum", ["スクラム"], ["sờ crăm", "x crăm"],
      ja_bad=["スクラム"]),
    t("daily scrum", ["デイリースクラム", "朝会"], [],
      ja_bad=["デイリースクラム"]),
    t("kanban", ["カンバン", "看板"], ["can ban"],
      ja_bad=["カンバン", "看板"]),
    t("roadmap", ["ロードマップ"], ["rôt máp"],
      vi_bad=["lộ trình"],
      ja_bad=["ロードマップ"]),
    t("milestone", ["マイルストーン"], ["mai sờ tôn"],
      vi_bad=["mốc quan trọng"],
      ja_bad=["マイルストーン"]),
    t("deadline", ["デッドライン"], ["đét lai", "đết lai"],
      vi_bad=["hạn chót", "thời hạn"],
      ja_bad=["デッドライン", "締め切り"]),
    t("schedule",
      ["スケジュール"],
      ["sờ kê diun", "kê điun"],
      vi_bad=["lịch trình", "kế hoạch"],
      ja_bad=["スケジュール", "予定"],
      vi_guard=["kế hoạch kinh doanh"]),
    t("kickoff", ["キックオフ"], ["kích óp"],
      ja_bad=["キックオフ"]),
    t("retrospective",
      ["レトロスペクティブ", "振り返り"],
      ["rê tờ rô spếch ti"],
      vi_bad=["nhìn lại", "tổng kết"],
      ja_bad=["レトロスペクティブ", "振り返り"]),
    t("demo", ["デモ"], ["đê mô"],
      vi_bad=["trình diễn"],
      ja_bad=["デモ"]),
    t("feedback", ["フィードバック"], ["phít bách"],
      vi_bad=["phản hồi", "góp ý"],
      ja_bad=["フィードバック"]),
    t("meeting", ["ミーティング"], ["mít tinh", "mí tinh"],
      vi_bad=["cuộc họp", "buổi họp"],
      ja_bad=["ミーティング"]),
    t("agenda", ["アジェンダ"], ["a gien đa"],
      vi_bad=["chương trình nghị sự"],
      ja_bad=["アジェンダ", "議題"]),
    t("standup", ["スタンドアップ"], ["x tăn đắp"],
      vi_bad=["họp đứng"],
      ja_bad=["スタンドアップ"]),
    t("project",
      ["プロジェクト"],
      ["pờ rô dếch", "prô dếch"],
      vi_bad=["dự án"],
      ja_bad=["プロジェクト"],
      vi_guard=["dự án bất động sản"]),
    t("team", ["チーム"], ["tim mờ"],
      vi_bad=["đội nhóm", "đội ngũ"],
      ja_bad=["チーム"]),
    t("stakeholder",
      ["ステークホルダー"],
      ["sờ têch hôn đơ"],
      vi_bad=["bên liên quan"],
      ja_bad=["ステークホルダー"]),
    t("MVP", ["エムブイピー"], ["mvp", "em vi pi"],
      ja_bad=["エムブイピー"]),
    t("POC", ["ピーオーシー"], ["poc", "pi ô xi"],
      ja_bad=["ピーオーシー"]),
    t("KPI", ["ケーピーアイ"], ["kpi", "kê pi ai"],
      ja_bad=["ケーピーアイ"]),
    t("OKR", ["オーケーアール"], ["okr", "ô kê a"],
      ja_bad=["オーケーアール"]),
    t("OK", ["オーケー", "オッケー"], ["ok", "ô kê", "ồ kê"],
      ja_bad=["オーケー", "オッケー"]),

    # =========================================================== CÔNG CỤ & NỀN TẢNG
    t("Slack", ["スラック"], ["sờ lắc", "xì lắc"],
      ja_bad=["スラック"]),
    t("Teams", ["チームズ", "チームス"], ["tim sờ"],
      ja_bad=["チームズ"]),
    t("Zoom", ["ズーム"], ["dum", "dùm mờ"],
      ja_bad=["ズーム"]),
    t("Jira", ["ジラ", "ジーラ"], ["di ra", "gi ra"],
      ja_bad=["ジラ", "ジーラ"]),
    t("Confluence", ["コンフルエンス"], ["con phlu ần"],
      ja_bad=["コンフルエンス"]),
    t("Notion", ["ノーション"], ["nâu sừn", "nô sần"],
      ja_bad=["ノーション"]),
    t("Linear", ["リニア"], ["li ni a"],
      ja_bad=["リニア"]),
    t("Asana", ["アサナ"], ["a sa na"],
      ja_bad=["アサナ"]),
    t("Trello", ["トレロ"], ["tờ rê lô"],
      ja_bad=["トレロ"]),
    t("Excel", ["エクセル"], ["ếch xeo", "ét xeo"],
      ja_bad=["エクセル"]),
    t("PowerPoint", ["パワーポイント", "パワポ"], ["pao poin"],
      ja_bad=["パワーポイント", "パワポ"]),
    t("Google Drive", ["グーグルドライブ"], ["gu gồ đờ rai"],
      ja_bad=["グーグルドライブ"]),
    t("Google Meet", ["グーグルミート"], ["gu gồ mít"],
      ja_bad=["グーグルミート"]),
    t("Gmail", ["ジーメール", "ジメール"], ["di meo", "gi meo"],
      ja_bad=["ジーメール"]),
    t("Chatwork", ["チャットワーク"], ["chát guơ"],
      ja_bad=["チャットワーク"]),
    t("Redmine", ["レッドマイン"], ["rét mai"],
      ja_bad=["レッドマイン"]),
    t("VS Code",
      ["ブイエスコード", "ビジュアルスタジオコード"],
      ["vi ét cốt", "vi ét cô đờ"],
      vi_bad=["Visual Studio Code"],
      ja_bad=["ブイエスコード"]),
    t("IntelliJ", ["インテリジェイ"], ["in tê li gei"],
      ja_bad=["インテリジェイ"]),
    t("Postman", ["ポストマン"], ["pốt man"],
      ja_bad=["ポストマン"]),
    t("Swagger", ["スワッガー"], ["x oa gơ"],
      ja_bad=["スワッガー"]),
    t("Sentry", ["セントリー"], ["xen tri"],
      ja_bad=["セントリー"]),
    t("Vercel", ["バーセル"], ["vơ xen"],
      ja_bad=["バーセル"]),
    t("Netlify", ["ネトリファイ"], ["nét lai phai"],
      ja_bad=["ネトリファイ"]),

    # =========================================================== WEB & KHÁC
    t("email",
      ["メール", "イーメール", "Eメール"],
      ["i meo", "e meo"],
      vi_bad=["thư điện tử"],
      ja_bad=["メール", "イーメール"]),
    t("chat", ["チャット"], ["chát"],
      vi_bad=["trò chuyện"],
      ja_bad=["チャット"]),
    t("comment", ["コメント"], ["com men", "cô men"],
      vi_bad=["bình luận", "nhận xét"],
      ja_bad=["コメント"]),
    t("share", ["シェア"], ["se a", "sê a"],
      vi_bad=["chia sẻ"],
      ja_bad=["シェア", "共有"]),
    t("link", ["リンク"], ["lin cờ", "linh cờ"],
      vi_bad=["liên kết", "đường dẫn"],
      ja_bad=["リンク"]),
    t("URL", ["ユーアールエル"], ["url", "diu a eo", "iu a eo"],
      ja_bad=["ユーアールエル"]),
    t("browser", ["ブラウザ", "ブラウザー"], ["bờ rao dơ"],
      vi_bad=["trình duyệt"],
      ja_bad=["ブラウザ"]),
    t("app", ["アプリ"], ["áp pờ"],
      vi_bad=["ứng dụng"],
      ja_bad=["アプリ"]),
    t("application", ["アプリケーション"], ["áp pli kê sần"],
      ja_bad=["アプリケーション"]),
    t("mobile", ["モバイル"], ["mô bai"],
      vi_bad=["di động"],
      ja_bad=["モバイル"],
      vi_guard=["điện thoại di động"]),
    t("web", ["ウェブ", "ウエブ"], ["guép", "quép"],
      ja_bad=["ウェブ"]),
    t("website", ["ウェブサイト", "ホームページ"], ["guép sai"],
      vi_bad=["trang web", "trang mạng"],
      ja_bad=["ウェブサイト", "ホームページ"]),
    t("domain", ["ドメイン"], ["đô mên"],
      vi_bad=["tên miền"],
      ja_bad=["ドメイン"]),
    t("license", ["ライセンス"], ["lai sần"],
      vi_bad=["giấy phép", "bản quyền"],
      ja_bad=["ライセンス", "免許"],
      vi_guard=["giấy phép lái xe", "giấy phép kinh doanh"]),
    t("open source", ["オープンソース"], ["ô pần sốt"],
      vi_bad=["nguồn mở"],
      ja_bad=["オープンソース"]),
    t("SaaS", ["サース", "サーズ"], ["saas", "sa at"],
      ja_bad=["サース"]),
    t("PaaS", ["パース"], ["paas", "pa at"],
      ja_bad=["パース"]),
    t("IaaS", ["イアース"], ["iaas", "i a at"],
      ja_bad=["イアース"]),
    t("access",
      ["アクセス", "アセス"],
      ["ắc xét", "ắc x"],
      vi_bad=["truy cập"],
      ja_bad=["アクセス", "アセス"]),
    t("file", ["ファイル"], ["phai", "phài"],
      vi_bad=["tệp", "tập tin", "hồ sơ"],
      ja_bad=["ファイル"],
      vi_guard=["hồ sơ bệnh án", "hồ sơ xin việc"]),
    t("folder", ["フォルダ", "フォルダー"], ["phôn đơ"],
      vi_bad=["thư mục"],
      ja_bad=["フォルダ"]),
    t("upload", ["アップロード"], ["áp lốt", "úp lốt"],
      vi_bad=["tải lên"],
      ja_bad=["アップロード"]),
    t("download", ["ダウンロード"], ["đao lốt", "đao lâu"],
      vi_bad=["tải xuống", "tải về"],
      ja_bad=["ダウンロード"]),
    t("update", ["アップデート"], ["áp đết", "úp đết"],
      vi_bad=["cập nhật"],
      ja_bad=["アップデート", "更新"]),
    t("upgrade", ["アップグレード"], ["áp gờ rết"],
      vi_bad=["nâng cấp"],
      ja_bad=["アップグレード"]),
    t("install", ["インストール"], ["in sờ ton", "in tôn"],
      vi_bad=["cài đặt"],
      ja_bad=["インストール"]),
    t("setup", ["セットアップ"], ["sét ắp", "xét ắp"],
      ja_bad=["セットアップ"]),
    t("config", ["コンフィグ"], ["con phích", "công phích"],
      vi_bad=["cấu hình"],
      ja_bad=["コンフィグ"]),
    t("environment",
      ["環境", "エンバイロンメント"],
      ["en vai rồn mần"],
      vi_bad=["môi trường"],
      ja_bad=["環境", "エンバイロンメント"],
      vi_guard=["môi trường sống", "bảo vệ môi trường"]),
    t("local", ["ローカル"], ["lô cồn", "lô côn"],
      vi_bad=["địa phương", "cục bộ"],
      ja_bad=["ローカル"],
      vi_guard=["người địa phương"]),
    t("remote", ["リモート"], ["ri một", "rê một"],
      vi_bad=["từ xa", "điều khiển từ xa"],
      ja_bad=["リモート", "遠隔"]),
    t("login", ["ログイン"], ["lóc in", "lo gin"],
      vi_bad=["đăng nhập"],
      ja_bad=["ログイン"]),
    t("logout", ["ログアウト"], ["lóc ao", "lo gao"],
      vi_bad=["đăng xuất"],
      ja_bad=["ログアウト"]),
    t("password", ["パスワード"], ["pát guốt", "pát quơ"],
      vi_bad=["mật khẩu"],
      ja_bad=["パスワード"]),
    t("account", ["アカウント"], ["ơ cao", "a cao ừn"],
      vi_bad=["tài khoản"],
      ja_bad=["アカウント", "口座"]),
    t("user", ["ユーザー", "ユーザ"], ["diu dơ", "iu dơ"],
      vi_bad=["người dùng", "người sử dụng"],
      ja_bad=["ユーザー", "ユーザ"]),
    t("admin", ["アドミン"], ["át min"],
      vi_bad=["quản trị viên"],
      ja_bad=["アドミン", "管理者"]),
    t("permission", ["パーミッション"], ["pơ mít sần"],
      vi_bad=["quyền hạn", "sự cho phép"],
      ja_bad=["パーミッション", "権限"]),
]


def main() -> None:
    seen = set()
    for e in ENTRIES:
        key = e["term"].lower()
        if key in seen:
            raise SystemExit(f"❌ Trùng thuật ngữ: {e['term']}")
        seen.add(key)

    out = Path(__file__).resolve().parent / "glossary_v2.json"
    out.write_text(
        json.dumps({"entries": ENTRIES}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8")
    print(f"✅ Đã ghi {len(ENTRIES)} thuật ngữ vào {out.name}")
    print("   Kiểm tra xong: đổi tên thành glossary.json rồi khởi động lại backend.")


if __name__ == "__main__":
    main()
